title: La Data Web Blog
description: Blog personal sobre datos, Power BI, Fabric, Azure y automatización.
lang: es-AR
timezone: America/Argentina/Jujuy

url: "https://ladataweb.github.io"
baseurl: "/blog-ladataweb"

author: Ibarrau
main_site_url: "https://ladataweb.com.ar"

socials:
  linkedin: "https://www.linkedin.com/"
  github: "https://github.com/ibarrau-pi"
  x: ""
  instagram: ""
  email: ""