title: La Data Web Blog
description: Blog comunitario sobre el universo de Data de la mano de Fabric, Power Bi, Azure Data Platform y extras.
lang: es-AR
timezone: America/Argentina/Buenos_Aires

url: "https://ladataweb.github.io"
baseurl: "/blog-ladataweb"

permalink: /:title/
excerpt_separator: "<!--more-->"

author: Ignacio Barrau
main_site_url: "https://ladataweb.com.ar"

logo: /assets/images/ldw-logo.png

socials:
  x: "https://x.com/ignacho_07"
  linkedin: "https://ar.linkedin.com/in/ignacio-barrau-b794b082"
  github: "https://github.com/ibarrau"
  subscribe: "https://www.ladataweb.com.ar/contacto.html?id=suscribirse"

paginate: 5
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate